states:
  BWC::Initial_:
    base: BWC::Initial
    configs:
      autoStartTime: 8.0
      initialFootstepList:
        - foot: Left
          footMidpose:
            translation: [0.15, 0.0, 0.0]
          startTime: 2.0
        - footMidpose:
            translation: [0.30, 0.0, 0.0]
        - footMidpose:
            translation: [0.45, 0.0, 0.0]
        - footMidpose:
            translation: [0.60, 0.0, 0.0]
        - footMidpose:
            translation: [0.75, 0.0, 0.0]
        - footMidpose:
            translation: [0.9, 0.0, 0.0]
        - footMidpose:
            translation: [0.9, 0.0, 0.0]
